// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/org-unit-cell/After.tsx": () => import("../components/mockups/org-unit-cell/After.tsx"),
  "./components/mockups/org-unit-cell/Before.tsx": () => import("../components/mockups/org-unit-cell/Before.tsx")
};
